### ISSUE TITLE
Schema for statefiles?

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#160]
I always thought that the [code](https://github.com/skorokithakis/catt/blob/master/catt/controllers.py#L258) I wrote to crudely validate contents of statefiles looked really ugly.
Do you think it would be worth the extra dependency to use something like [jsonschema](https://github.com/Julian/jsonschema) instead?

**Comment by skorokithakis** [comment]
The only confusing thing there is the `next(iter(` thing, are you just doing that to get `[0]`? Otherwise, it doesn't look terrible, but I like [schema](https://github.com/keleshev/schema) a lot and use it frequently, so I wouldn't be against it. It doesn't look like it's worth it in this particular case, though.

**Comment by theychx** [comment]
Cheers

> the next(iter( thing

You can't use indexes on ```dict_values``` objects, so I would have to listyfi..
