### ISSUE TITLE
Detect mime type of local files by content rather than extension

### ISSUE THREAD

**Issue by jakkarth** [skorokithakis/catt#262]
Hi there! I've got a collection of image files I like to cast to my tv in a slideshow. Some of them are named whatever.jp**e**g. The e means it's not jpg, and the mime-from-file-extension method will return video/mp4 in this case, which won't display correctly on the tv.

Would it be possible to use something like [python-magic](https://github.com/ahupp/python-magic) to detect the appropriate mime type based on the local file's contents, rather than its problematic non-standardized extension? I wouldn't suggest using this for remote playback, but for local files this seems simpler (delegates mime determination to a maintained library) and more accurate (can still handle files when they have the wrong extension).

**Comment by skorokithakis** [comment]
That would certainly be possible, but, as you say, it's not a great method because it adds an extra dependency for not much benefit (it only works for local files) *and* we'd have to keep the old way anyway for remote files.

I have added `.jpeg` as an extension, however, so it gets properly detected, and hopefully that will fix the problem for the vast majority of cases.
