### ISSUE TITLE
casting of photos does not work anymore

### ISSUE THREAD

**Issue by Gunstick** [skorokithakis/catt#339]
probably due to a chromecast update, as I did not change anything.
Casting of mp4, or webpages still works, but jpg is not. The chromecast reacts but does not display the picture.
My workaround is that I convert pictures to videos, but that's cumbersome.
Casting from google photos app still works
I installed with pip the latest version of catt. Also tried on another PC. No success.

**Comment by theychx** [comment]
Thank you for reporting this.
As I suspected, the problem is not with firmware, but rather with the default/generic chromecast app, that `catt` uses for most things. This app is very frequently updated, and sometimes various stuff stops working for a few weeks.

@skorokithakis I'd like to discuss various approaches to avoiding these annoyances (chat), whenever its convenient for you.

**Comment by Gunstick** [comment]
I have daily backups, can you hint me in directions which files I may need to restore to get the photo functionality back?

**Comment by theychx** [comment]
The generic chromecast app is loaded dynamically from googles servers by your chromecast, so this cant be fixed by rolling back stuff on your own box.

**Comment by theychx** [comment]
This seems to be working again. When time permits, we'll continue work on #340, so users wont be bothered by intermittent generic chromecast app issues such as this one.
