### ISSUE TITLE
Relax click dependency

### ISSUE THREAD

**Issue by Artturin** [skorokithakis/catt#354]
it was tightened because click 8 didn't work with python3.5  #311

**Comment by skorokithakis** [comment]
I imagine it would be better to install Catt with pipx, so dependencies won't be an issue.

**Comment by SuperSandro2000** [comment]
> I imagine it would be better to install Catt with pipx, so dependencies won't be an issue.

That will most likely not work with NixOS and is also not the goal for a distro.

**Comment by skorokithakis** [comment]
Doesn't NixOS install separate dependencies for each package? Also, does click 8 work with 3.5 now?

**Comment by SuperSandro2000** [comment]
> Doesn't NixOS install separate dependencies for each package?

Yes but we can't mix different click versions within the pythonPackage set because of limitations of python.

> Also, does click 8 work with 3.5 now?

I don't know, we dropped 3.5 a while ago.

**Comment by skorokithakis** [comment]
Hmm, I see, but isn't it a bit backwards that I have to change my dependency tree (and potentially drop older versions) because of a design issue in a downstream packaging software package?

**Comment by SuperSandro2000** [comment]
> potentially drop older versions

No one should realistically use python 3.5 anyway and yes it was dropped https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-0.

> of a design issue in a downstream packaging software package?

This is more a design issue of Python rather than nixpkgs. Other software ecosystems do not have such problems.

**Comment by skorokithakis** [comment]
Sure, 3.5 is EOLed, meaning that bugs will not be fixed, but I don't tend to treat this as "it's okay to break these old versions for little reason". I guess we can relax the requirement in this case, but creating a virtualenv per cli app is a better solution in general (like pipx does).

**Comment by SuperSandro2000** [comment]
> but creating a virtualenv per cli app is a better solution in general (like pipx does)

but it is also a total waste of disk space and creates a lot of managing overhead if you have 20 or more of them.

**Comment by skorokithakis** [comment]
@SuperSandro2000 well, the alternative is to get every single maintainer to agree to have compatible dependencies, so...

**Comment by FranciscoPombal** [comment]
@skorokithakis 

> Sure, 3.5 is EOLed, meaning that bugs will not be fixed, but I don't tend to treat this as "it's okay to break these old versions for little reason".

EOL is not a "little reason". EOL means: "cease efforts to explicitly support it asap".

Security and support should be taken seriously. No user has the right to say "you caused breakage because you dropped support for an EOL version"; this is a contradiction, as dropping support for EOL stuff is never breakage by definition. It is the user's responsibility to update their systems, developers should not burden themselves with supporting EOL versions.

Otherwise, because of a few bad apples that don't keep their systems up to date, the majority suffers.
For instance, for development I use virtual environments of course, but I also have a script that does `python3 -m pip install --upgrade --user <many packages>` to keep my global user packages updated, because there are a bunch of python packages that are useful to have accessible from any shell, like `yt-dlp` and `catt` - without having to `source` a virtual environment, which as mentioned above is not a (good) solution.

But because `catt` has not been updated in PyPi for a very long time due to wanting to support EOL python versions, I had to resort to one of the following workarounds, neither of which ideal, and each a hurdle for less experienced users who just want to install and use `catt` along with other packages:

- Install `"Click<8,>=7.1.2`, hoping that doesn't conflict with other packages, install the remaining dependencies manually, then install `catt` with `python3 -m pip install --user --upgrade --no-deps "catt"`. `--no-deps` is needed otherwise it will pull the dead `youtube-dl` package, so more headaches for those who want to use `yt-dlp` in peace.
- Install `cat` from git `master` instead of a PyPi release: `python3 -m pip install --user --upgrade git+https://github.com/...`

I see that the mentioned problems are already fixed in `master` at the time of writing, but there is still no new PyPi release with those changes, so the overall issue persists.

Please take this as a learning experience for the future when a similar situation arises.

This post may sound harsh and rant-y, but, in the grand scheme of things, this situation with `catt` is actually not that bad.
See the [Calibre author's original stance on migrating to Python 3](https://teddit.net/r/linux/comments/9wodtq/calibre_wont_migrate_to_python_3_author_says_i_am/) for an extreme example of what not to do with regards to managing EOL and technical debt (fortunately, he did eventually change his mind in time to avoid a disaster).

**Comment by FranciscoPombal** [comment]
@skorokithakis 

Actually, it seems fe9097565767e255b146b5ad35f5a7486c5fa922 needs a fixup to port `stream_info.py` (and also `test_catt.py`) to use `yt-dlp`.

Here are the docs for that: https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp, and this is the most relevant bit:

> **Tip**: If you are porting your code from youtube-dl to yt-dlp, one important point to look out for is that we do not guarantee the return value of `YoutubeDL.extract_info` to be json serializable, or even be a dictionary. It will be dictionary-like, but if you want to ensure it is a serializable dictionary, pass it through `YoutubeDL.sanitize_info` as shown in the example above

**Comment by skorokithakis** [comment]
@FranciscoPombal I've released another version with the relaxed Click dependency, though I really do recommend using `pipx`. About the fixup, could you open another ticket so we can track that there? Thank you!

**Comment by anthonyrocom** [comment]
The latest Docker build fails with the error below:

FROM python:3.7
RUN pip install catt

Running catt results in:

```
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 5, in <module>
    from catt.cli import main
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 14, in <module>
    from .controllers import CastState
  File "/usr/local/lib/python3.7/site-packages/catt/controllers.py", line 22, in <module>
    from .stream_info import StreamInfo
  File "/usr/local/lib/python3.7/site-packages/catt/stream_info.py", line 4, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
Traceback (most recent call last):
  File "/usr/local/bin/catt", line 5, in <module>
    from catt.cli import main
  File "/usr/local/lib/python3.7/site-packages/catt/cli.py", line 14, in <module>
    from .controllers import CastState
  File "/usr/local/lib/python3.7/site-packages/catt/controllers.py", line 22, in <module>
    from .stream_info import StreamInfo
  File "/usr/local/lib/python3.7/site-packages/catt/stream_info.py", line 4, in <module>
    import youtube_dl
ModuleNotFoundError: No module named 'youtube_dl'
```
