### ISSUE TITLE
Pychromecast is dropping suppport for Python 2

### ISSUE THREAD

**Issue by theychx** [skorokithakis/catt#57]
Howdy.
Pychromecast will no longer support python 2, as of next release (because python-zeroconf will drop python 2 support).
I have a slew of minor PR's coming up after the controllers refactor PR (which is ready, by the way :smiley: ) has been merged. After that I humbly suggest that we make python 3.5 the min. requirement for ```catt```, as this is now available for all major OS'es (the new min. requirement for Pychromecast will be 3.4, I'm just more keen on 3.5).

**Comment by skorokithakis** [comment]
Hello!  
I'm generally loath to remove support for things. If Pychromecast removes support for 2, there's not much we can do, but I generally like erring on the site of being compatible. If there's a version of 3 we need, then by all means, we should use it, but we shouldn't go around turning everything into f-strings or whatever just because.

Other than that, I generally agree with you (I'm reviewing #55 now, by the way), although I would like to keep support for 3.4 as my Raspbian doesn't have 3.5 yet and I can imagine many people using catt on a Raspberry Pi.

**Comment by theychx** [comment]
Min. 3.4 is cool, although raspbian stretch has 3.5, so I'm not sure I understand that argument. But as long as we commit to no longer care about what might not work for <3.4 then I'm happy (no more try except clauses around import statements etc.).

**Comment by skorokithakis** [comment]
(It may have been a while since I last upgraded my raspi)

**Comment by theychx** [comment]
@skorokithakis Please consider making a final python2 compatible release, so we can move on. As for #73, I'm honestly reluctant to invest time in fixing this myself, as I plan to completely rework the server script (I want ```catt``` to spawn an independent process that automatically dies when the cc has stopped/finished playing). If this pans out, I also intend to extend this further, by implementing #46.

**Comment by skorokithakis** [comment]
@theychx Certainly, I can release now. We're sorted for all the py2 compatible things we wanted to release, right?

About #73, I've been meaning to retest, but I'm kind of blocked because `catt` can't locate my Chromecast. I'll debug that when I have some time and try to fix it.

**Comment by skorokithakis** [comment]
Released `0.5.5` and added README information.

**Comment by theychx** [comment]
> We're sorted for all the py2 compatible things we wanted to release, right?

Yep. I'll make a PR that removes py2 compat code after you've made the release.
